{
    "name": "@perfective/error",
    "version": "0.2.0-alpha.1",
    "description": "Functions for the Error and other types to handle exceptions",
    "keywords": [
        "error",
        "error chaining",
        "error handling",
        "exception",
        "exception chaining",
        "exception handling",
        "panic",
        "stack trace",
        "throwable",
        "es6",
        "es2015"
    ],
    "author": "Andrey Mikheychik <a.mikheychik@gmail.com>",
    "homepage": "https://github.com/perfective/js",
    "license": "MIT",
    "main": "dist/index.js",
    "types": "dist/index.d.ts",
    "files": [
        "dist"
    ],
    "sideEffects": false,
    "scripts": {
        "build": "tsc --project ./tsconfig.build.json",
        "build:clean": "npm run clean && npm run build",
        "clean": "rm -rf dist && rm -f *.tsbuildinfo",
        "lint": "npm run lint:eslint; npm run lint:tslint",
        "lint:eslint": "eslint --fix --ext .ts ./src",
        "lint:tslint": "tslint --fix --project ./tsconfig.lint.json",
        "test": "jest",
        "test:clean": "jest --clearCache",
        "test:verbose": "jest --verbose"
    }
}
